source 'https://rubygems.org'

gem 'rails', '4.1.6'

gem 'mysql2', group: :mysql
gem 'pg', group: :postgres

gem 'sass-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end



group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'thin'
  gem 'quiet_assets'
end



# UI
gem 'hirb'
gem 'font-awesome-rails'
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'haml'
gem 'simple_form', '~> 3.0.0.rc'

gem 'nokogiri'

gem 'kramdown'


gem 'ancestry'
gem 'acts_as_list'


gem 'cocaine'
gem 'paperclip'


gem 'kaminari'
gem 'kaminari-bootstrap'



gem 'dalli'
gem 'exception_notification'

gem 'newrelic_rpm', group: :new_relic
