language: ruby
rvm:
   - 2.0
   - 2.1
   - 2.2
   - jruby-9.0.0.0
   - jruby
   - rbx-2

 env:
   - "SUITE=units       DB=postgresql"
...	...
@@ -27,6 +28,13 @@ matrix:
     # https://github.com/jruby/jruby/issues/779
     - rvm: jruby
 before_install:
   # https://github.com/travis-ci/travis-ci/issues/4720
   - if [[ ${TRAVIS_RUBY_VERSION} =~ jruby-9\.0 ]] ;
     then
       rvm get master ;
       rvm use ${TRAVIS_RUBY_VERSION} --install ;
       ruby --version ;
     fi
   - "sudo apt-get update -qq"
   - "sudo apt-get --no-install-recommends install bzr cvs git mercurial subversion"
 script:
...	...
@@ -38,6 +46,6 @@ script:
   - cd cms
   - "RUN_ON_NOT_OFFICIAL='' RUBY_VER=1.9 BRANCH=trunk bundle exec rake config/database.yml"
   - "bundle install"
   - export TEST_SUITE=${SUITE}
   - "JRUBY_OPTS=-J-Xmx1024m bundle exec rake ci"
   - JRUBY_OPTS='-J-Xmx1024m -J-XX:MaxPermSize=1024m' bundle exec rake ci
   - exec rails c
 notifications:
   email: false
...	...
