source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.1.8'

gem 'mysql2', '~> 0.3.18', group: :mysql
gem 'pg', group: :postgres


# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'    #, '1.11.1'
gem 'jquery-ui-rails' #, '1.11.2'
gem 'morrisjs-rails'
gem 'raphael-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]




group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'thin' # Server
  gem 'quiet_assets'
end


gem 'devise', github: 'plataformatec/devise'


# UI
gem 'hirb'
gem 'font-awesome-rails', '~> 4.0.3.1'
gem 'bootstrap-sass', '2.3.2.1'
gem 'haml-rails'
gem 'haml'
gem 'simple_form', '~> 3.0.0.rc'


gem 'kramdown'


gem 'ancestry'  # bäume
gem 'acts_as_list' # reihenfolge

gem 'paper_trail', '~> 3.0.2' # versionen
gem 'diffy'

gem 'cancan'

gem 'ransack'

gem 'cocaine'
gem 'paperclip'


gem 'kaminari'

## Bootstrap 3:
# gem 'kaminari-bootstrap', '~> 3.0.1'

## Bootstrap 2:
gem 'kaminari-bootstrap', '~> 0.1.3'



gem 'dalli'
gem 'exception_notification'
gem 'ensure_valid_encoding'


gem "rails-erd"

gem 'newrelic_rpm'
